### ISSUE TITLE
variable argument length

### ISSUE THREAD

**Issue by konsumer** [konsumer/Qbs4QJS#2]
There may just be no way around it. But this issue is for discussion around that.

One thing I lost was the ability to have variable argument-lengths.

For example, with `FileInfo.joinPaths`.

**Comment by bjorn** [comment]
This has been requested in [QTBUG-70677](https://bugreports.qt.io/browse/QTBUG-70677), though without any news since it was opened in 2018. :-/

**Comment by konsumer** [comment]
Bummer. I'm honestly ok with using an array. it seems to work fine, if not minorly annying. I could also see wrapping it in javascript-space:

```js
FileInfo.joinPaths = (...args) => FileInfo._joinPaths
```

**Comment by bjorn** [comment]
Right, we can execute some JS code as well to fill in those parts. We can resolve the constructor exception the same way and make the call to `open` automatic again (and rename to `_open` to indicate it's not meant to be used).

**Comment by konsumer** [comment]
Since I am way stronger with JS, it appeals to me to solve the inter-op issues in JS-space.

This would solve the dynamic args issue, and the [no throw in constructor](https://github.com/konsumer/Qbs4QJS/issues/4) issue.

Should I make a scriptmanager, so the C++ user can do something like this:

```cpp
ScriptManager manger(jsEngine, ["File", "FileInfo", "Process"]);
```

It would limit what they were named in JS, but also make it easier to just add what is needed, and since the class would have access to the `jsEngine`, it could inject js-space wrappers and stuff.

@rweickelt offered a [workaround](https://stackoverflow.com/questions/52407560/how-to-make-q-invokable-method-that-takes-variable-number-of-arguments-from-qml/52428628#52428628) in email. This demonstrates a slightly different approach using [qmlRegisterSingletonType](https://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterSingletonType) with inline javascript-code.

**Comment by konsumer** [comment]
Hmm, to try it out, I did this, inside `Qbs4QJS` namespace:

```cpp
class ScriptBinaryFile
{
public:
	ScriptBinaryFile(QJSEngine jsEngine, const QString jsName = "BinaryFile") {
		jsEngine.globalObject().setProperty("BinaryFile", jsEngine.newQMetaObject(&BinaryFile::staticMetaObject));
	}
};

// called like this:
Qbs4QJS::ScriptBinaryFile fbin(jsEngine);
```

and I get this error:

```
ERROR: In file included from /usr/include/qt/QtCore/qobject.h:46,
                 from /usr/include/qt/QtCore/QObject:1,
                 from /home/konsumer/Documents/otherdev/Qbs4QJS/default/Qbs4QJS.6f304c2a/qt.headers/../../../binaryfile.h:1,
                 from /home/konsumer/Documents/otherdev/Qbs4QJS/default/Qbs4QJS.6f304c2a/qt.headers/moc_binaryfile.cpp:10:
/usr/include/qt/QtCore/qobjectdefs.h:114:5: error: class definition may not be declared a friend
  114 |     friend Q_DECL_CONSTEXPR const QMetaObject *qt_getEnumMetaObject(ENUM) noexcept { return &staticMetaObject; } \
      |     ^~~~~~
```

Do I need to do it some other way?

**Comment by konsumer** [comment]
I implemented them, like above, but I can put it back, if it seems like a bad idea. I'm going to try to add the variable length argument stuff, now.

**Comment by konsumer** [comment]
So, I got this working over on #4, then added the dynamic args stuff for `FileInfo.joinPaths`. It auto-closed, but feel free to re-open, if this seems like a bad solution.
